"""
Pydantic models for structured API requests and responses.
Ensures the AI agent outputs predictable, parseable JSON.
"""
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class InvestigationRequest(BaseModel):
    """The question asked by the business user."""
    question: str = Field(..., description="The natural language business question.")
    context: Optional[str] = Field(None, description="Optional context, e.g., 'Compare March to February'.")

class Hypothesis(BaseModel):
    """A single hypothesis generated by the agent."""
    id: str = Field(..., description="Unique ID, e.g., 'H1'.")
    description: str = Field(..., description="Description of the hypothesis.")
    test_method: str = Field(..., description="How this hypothesis will be tested using data.")

class EvidenceItem(BaseModel):
    """A piece of evidence collected from testing a hypothesis."""
    hypothesis_id: str
    metric: str
    finding: str
    quantitative_value: Optional[float] = None
    sample_size: Optional[int] = None
    confidence: str = Field(..., description="High, Medium, or Low")

class InvestigationResponse(BaseModel):
    """The final structured answer from the AI Agent."""
    executive_summary: str
    hypotheses_tested: List[Hypothesis]
    evidence: List[EvidenceItem]
    root_causes: List[str]
    recommendations: List[str]
    limitations: str